import { z } from 'zod';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import { getActiveSession } from './session.js';

// Converts a live exploratory session into a YAML test spec compatible with
// `sf agent test run-eval` (Salesforce CLI 2026-05-20, Beta). This turns the
// plugin into an upstream of the native pipeline: explore in Claude/Codex,
// then export the discovered scenarios as regression tests Salesforce can run
// in CI. See: https://developer.salesforce.com/docs/ai/agentforce/guide/agent-dx-test-customize.html

export const generateTestSpecSchema = z.object({
  sessionId: z
    .string()
    .describe('Session ID of an active or recently-ended exploratory session'),
  agentApiName: z
    .string()
    .describe('Agent API name the test spec should target'),
  suiteName: z
    .string()
    .describe('Name for the generated test suite (kebab-case recommended)'),
  expectedSubagent: z
    .string()
    .optional()
    .describe('Optional: subagent the spec should assert was routed to'),
  expectedActions: z
    .array(z.string())
    .optional()
    .describe('Optional: actions the spec should assert were invoked'),
  outputPath: z
    .string()
    .optional()
    .describe('Where to write the YAML file. Defaults to sfagent-reports/<suiteName>.yaml'),
});

interface TestCase {
  id: string;
  utterance: string;
  conversationHistory?: Array<{ role: 'user' | 'agent'; message: string }>;
  expectedSubagent?: string;
  expectedActions?: string[];
}

function toYaml(spec: {
  suite: string;
  agent: string;
  cases: TestCase[];
}): string {
  const lines: string[] = [];
  lines.push(`# Generated by sfagent-tools from an exploratory session`);
  lines.push(`# Run with: sf agent test run-eval --spec ${spec.suite}.yaml --target-org <alias>`);
  lines.push(`suite: ${spec.suite}`);
  lines.push(`agent:`);
  lines.push(`  apiName: ${spec.agent}`);
  lines.push(`cases:`);
  for (const tc of spec.cases) {
    lines.push(`  - id: ${tc.id}`);
    lines.push(`    utterance: ${JSON.stringify(tc.utterance)}`);
    if (tc.conversationHistory?.length) {
      lines.push(`    conversationHistory:`);
      for (const turn of tc.conversationHistory) {
        lines.push(`      - role: ${turn.role}`);
        lines.push(`        message: ${JSON.stringify(turn.message)}`);
      }
    }
    if (tc.expectedSubagent) {
      lines.push(`    expectedSubagent: ${tc.expectedSubagent}`);
    }
    if (tc.expectedActions?.length) {
      lines.push(`    expectedActions:`);
      for (const action of tc.expectedActions) {
        lines.push(`      - ${action}`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

export async function generateTestSpec(args: z.infer<typeof generateTestSpecSchema>) {
  const session = getActiveSession(args.sessionId);
  if (!session) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Session ${args.sessionId} not found. Run an exploratory session first, then call generate_test_spec before end_session.`,
        },
      ],
    };
  }

  if (!session.messages.length) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Session ${args.sessionId} has no messages. Send at least one message before generating a spec.`,
        },
      ],
    };
  }

  // Build one test case per user utterance, using the messages that came
  // before it as conversation history. This preserves multi-turn context the
  // way Agentforce DX expects it.
  const cases: TestCase[] = [];
  for (let i = 0; i < session.messages.length; i++) {
    const msg = session.messages[i];
    if (msg.role !== 'user') continue;

    const priorTurns = session.messages.slice(0, i).map((m) => ({
      role: m.role,
      message: m.content,
    }));

    cases.push({
      id: `${args.suiteName}-turn-${cases.length + 1}`,
      utterance: msg.content,
      conversationHistory: priorTurns.length ? priorTurns : undefined,
      expectedSubagent: args.expectedSubagent,
      expectedActions: args.expectedActions,
    });
  }

  const yaml = toYaml({
    suite: args.suiteName,
    agent: args.agentApiName,
    cases,
  });

  const outputPath = args.outputPath ?? `sfagent-reports/${args.suiteName}.yaml`;
  const dir = dirname(outputPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(outputPath, yaml, 'utf-8');

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(
          {
            suiteName: args.suiteName,
            cases: cases.length,
            outputPath,
            nextStep: `sf agent test run-eval --spec ${outputPath} --target-org <alias>`,
            preview: yaml.split('\n').slice(0, 15).join('\n') + '\n...',
          },
          null,
          2
        ),
      },
    ],
  };
}
